Hardik
vaibhavBhattad/ruby_Kylas pull request #3
Opened 2023-02-22 11:55 UTC by hardik-jade

Added Hangman and Inventory Cart Code Please Review It

2023-02-22 12:43 UTC, MayurJain-Kylas requested changes
In test cases it would be better if the variables are declared in before do block and then used as a parameter in it block

2023-02-22 12:57 UTC, hardik-jade commented
> ould be better if the variables are declared in before do block and then used as a pa

thank you @MayurJain-Kylas Changes made

2023-02-22 14:35 UTC, MayurJain-Kylas approved these changes

2023-02-23 06:38 UTC, dixit-krishnankit commented on hardik/hangman/main.rb
> +# --------------------------------------------
You can remove unnecessary comments

2023-02-23 06:39 UTC, dixit-krishnankit commented on hardik/cart/cart_with_object.rb
> +  puts '-----------------------------------'
Menu function can be created

2023-02-23 06:48 UTC, Makwana-Jigar requested changes

2023-02-23 06:48 UTC, Makwana-Jigar commented on hardik/hangman/main.rb
> +  input_char = gets.chomp[0].upcase
The way you are taking user input, it throws an error when user don't give any input and just press enter. I think in this case either it should reduce the user chances by considering it as wrong choice or it should prompt again about taking user input. And also may be you can ignore the trailing spaces of user input

2023-02-23 06:48 UTC, Makwana-Jigar commented on hardik/cart/main.rb
> +# -------------------------------------------------------
Here there(add to cart, update to cart, etc) is a problem that when user enter any invalid id then before taking quantity as input it should prompt an error message like id is invalid because it doesn't make any sense for asking the quantity if the product is not available in inventory. Also you should print messages like successfully added or removed or updated or don't have enough quantity like that.

2023-02-23 06:48 UTC, Makwana-Jigar commented on hardik/cart/service.rb
> +    return true
While updating the quantity it's not checking that inventory has enough quantity or not and also if it has it's not even updating to the inventory. In view cart it just show the updated quantity but the total price is not reflected according to quantity and also quantity in inventory should also updated but it's not.

2023-02-23 08:36 UTC, Hardik-Jade commented on hardik/hangman/main.rb
> +  input_char = gets.chomp[0].upcase
resolved

2023-02-23 08:39 UTC, Hardik-Jade commented on hardik/cart/main.rb
> +# -------------------------------------------------------
this was done deliberately to execute rspecs code flawleesly

2023-02-23 08:47 UTC, Hardik-Jade commented on hardik/cart/cart_with_object.rb
> +  puts '-----------------------------------'
done

2023-02-23 08:48 UTC, Hardik-Jade commented on hardik/hangman/main.rb
> +# --------------------------------------------
done

2023-02-23 17:37 UTC, Makwana-Jigar approved these changes

2023-02-24 05:14 UTC, dixit-krishnankit approved these changes

2023-03-02 13:33 UTC, ajit-selldo requested changes
Also, add screenshots for test cases. Few comments apply at multiple places, but commented only once, please make changes as required.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +load 'service.rb'
Use require here.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +# # * testing add_product method
Remove obvious comments.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +      name = 'nirma'
The scope of name, quantity and price is for before only. You may need to use instance variables here instead.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +    it 'it should return an object having key as name, quantity and price' do
Double `it`
> it 'should return product object'

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +  context 'when testing add_product function' do
> context `when adding product details`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +    end
Use a single blank line between before and it

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +  context 'testing add_to_cart function' do
> context 'when adding product to cart'

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +      expect(result).to eq(false)
Test case does not match description

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +  context 'testing remove_from_cart function' do
> context 'when removing product from cart'

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_rspec.rb
> +    it 'should return true if the item is removed from the cart' do
> it 'should return true`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    @products = Array.new(0)
You can also use `[]` here

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    puts '------------------------------------------'
You can store these dashes string in an object and use it here to avoid inconsistency and increase readability

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +      puts "#{index} \t #{item['name']} \t #{item['quantity']} \t\t #{item['price']}"
index here will start with 0. We should use index starting with 1.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    id = gets.chomp.to_i
If I enter some characters here, `.to_i` will convert it to `0` and it will then take the first product according to below logic. May we avoid this?

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    quantity = gets.chomp.to_i
Same for quantity. You should check if `gets.chomp` returns a valid Integer value.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +      @cart_item.push({
Array name should be plural as it has multiple elements.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    @cart_item.delete_at(id)
If we are deleting item from cart, are we adding the quantity in @products?

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +  def add_to_cart
According to below logic, this can be renamed to `add_to_cart_and_update_inventory`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +    @cart_item.each do |product_item|
See if we can do this using `inject`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +  case choice
You may use a hash to store these key values and avoid write these big `case when end`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/cart_with_object.rb
> +  when '8'
You can use a bad character (Number not between 1 to 7) also to exit.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/main.rb
> +        puts 'enter the id of product'
Use properly formatted sentences with proper punctuations

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/main.rb
> +        puts 'enter the id of product'
> Ex: `Enter Product ID`

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/cart/service.rb
> +
Extra blank line

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/hangman/main.rb
> +    puts "\nCongratulations you won"
You can do it like this. The readability of message is intact here.
> puts
puts "Congratulations! You Won."

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/hangman/main.rb
> +    TARGET.each_char.with_index do |letter, index|
We can refactor this loop. Please check.

2023-03-02 13:33 UTC, ajit-selldo commented on hardik/hangman/main.rb
> +puts 'Welcome to the Hangman Game'
Missing specs for hangman game.

2023-07-03 09:17 UTC, closed without merging